services:
  app:
    build: .
    container_name: holiday_service
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
