spring.application.name=holidays-service
spring.threads.virtual.enabled=true
api.base-url: https://date.nager.at/api/v3

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

